package com.mo008.crdm.models.supplier.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplierCar<M extends BaseSupplierCar<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setSupplierId(Integer supplierId) {
		set("supplier_id", supplierId);
	}

	public Integer getSupplierId() {
		return get("supplier_id");
	}

	public void setCarNo(String carNo) {
		set("car_no", carNo);
	}

	public String getCarNo() {
		return get("car_no");
	}

	public void setDateline(Integer dateline) {
		set("dateline", dateline);
	}

	public Integer getDateline() {
		return get("dateline");
	}

	public void setSort(Integer sort) {
		set("sort", sort);
	}

	public Integer getSort() {
		return get("sort");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreater(Integer creater) {
		set("creater", creater);
	}

	public Integer getCreater() {
		return get("creater");
	}

	public void setUpdater(Integer updater) {
		set("updater", updater);
	}

	public Integer getUpdater() {
		return get("updater");
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public Boolean getDeleteFlag() {
		return get("delete_flag");
	}

}
