/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.device;


import com.mo008.crdm.models.device.base.BaseDeviceData;
import com.mo008.util.SubmeterKit;

import goja.core.annotation.TableBind;
import goja.core.sqlinxml.SqlKit;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "mo_device_data")
public class DeviceData extends BaseDeviceData<DeviceData> {
    public static final  DeviceData dao              = new DeviceData();
    private static final long       serialVersionUID = 7060601052279122192L;


    /**
     * 通过汽车id查询最新的一条监控数据
     *
     * @param carId 汽车ID
     * @return 最新的监控数据
     */
    public DeviceData findByCarAndCurrent(long carId) {
        final String sql = SqlKit.sql("deviceData.findByCarAndCurrent");
        final String invokeSql = SubmeterKit.converGpsTable(sql);
        return findFirst(invokeSql, carId);
    }

    /**
     * 通过设备号查询设备监控记录
     *
     * @param deviceSn
     * @return
     */
    public DeviceData findByDeviceSn(String deviceSn) {
        return findFirst(SqlKit.sql("deviceData.findByDeviceSn"), deviceSn);
    }

    /**
     * 通过id查询然后更新信息
     *
     * @param id
     * @return
     */
    public DeviceData findByIdMore(int id) {
        final String sql = SqlKit.sql("deviceData.findByIdMore");
        final String invokeSql = SubmeterKit.converGpsTable(sql);
        return findFirst(invokeSql, id);
    }

    public DeviceData findByDeviceId(long deviceId) {
        return findFirst(SqlKit.sql("deviceData.findByDeviceId"), deviceId);
    }

    public void setDefaultValue() {
        this.setFlagMileage(0);
        this.setFlagSpeed(0);
        this.setPressureFlag(0);
        this.setPmValueFlag(0);
        this.setTemperature1Flag(0);
        this.setTemperature2Flag(0);
        this.setTemperature3Flag(0);
        this.setTemperature4Flag(0);
        this.setUreaPositionFlag(0);
        this.setUreaTemperatureFlag(0);
    }
}
