/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.device;


import com.mo008.crdm.models.device.base.BaseDeviceAuthBatch;

import goja.core.StringPool;
import goja.core.annotation.TableBind;
import goja.core.sqlinxml.SqlKit;
import com.jfinal.plugin.activerecord.Db;

import com.google.common.collect.Lists;

import org.apache.commons.lang3.StringUtils;

import java.util.Collections;
import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "mo_device_auth_batch")
public class DeviceAuthBatch extends BaseDeviceAuthBatch<DeviceAuthBatch> {
    public static final DeviceAuthBatch dao = new DeviceAuthBatch();
    private static final long serialVersionUID = -4938069212343852954L;

    public DeviceAuthBatch findInfoByUser(int authBatchId) {
        return findFirst(SqlKit.sql("device.authbatch.findInfoByUser"), authBatchId);
    }

    public boolean changeByDeleteStatus(String[] ids) {

            final String question_mark =
                    StringUtils.repeat(StringPool.QUESTION_MARK, StringPool.COMMA, ids.length);
            List<Object> params = Lists.newArrayList();
            params.add(Status.DELETE);
            Collections.addAll(params, ids);
            return Db.update("update mo_device_auth_batch set status = ? where id in ( " + question_mark + ")", params.toArray()) >= 0;
    }


    public interface Status {
        int NEW = 1;
        int GENERATE = 2;
        int DELETE = 3;
    }
}
