/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.device.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceDataHistory<M extends BaseDeviceDataHistory<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getNumber("id").intValue();
	}

	public void setDeviceId(Integer deviceId) {
		set("device_id", deviceId);
	}

	public Integer getDeviceId() {
		return get("device_id");
	}

	public void setFwhVersion(String fwhVersion) {
		set("fwh_version", fwhVersion);
	}

	public String getFwhVersion() {
		return get("fwh_version");
	}

	public void setSoftwareVersion(String softwareVersion) {
		set("software_version", softwareVersion);
	}

	public String getSoftwareVersion() {
		return get("software_version");
	}

	public void setObd(java.math.BigDecimal obd) {
		set("obd", obd);
	}

	public java.math.BigDecimal getObd() {
		return get("obd");
	}

	public void setAfterKm(java.math.BigDecimal afterKm) {
		set("after_km", afterKm);
	}

	public java.math.BigDecimal getAfterKm() {
		return get("after_km");
	}

	public void setSpeed(java.math.BigDecimal speed) {
		set("speed", speed);
	}

	public java.math.BigDecimal getSpeed() {
		return get("speed");
	}

	public void setEngineSpeed(java.math.BigDecimal engineSpeed) {
		set("engine_speed", engineSpeed);
	}

	public java.math.BigDecimal getEngineSpeed() {
		return get("engine_speed");
	}

	public void setTorque(java.math.BigDecimal torque) {
		set("torque", torque);
	}

	public java.math.BigDecimal getTorque() {
		return get("torque");
	}

	public void setNox(java.math.BigDecimal nox) {
		set("nox", nox);
	}

	public java.math.BigDecimal getNox() {
		return get("nox");
	}

	public void setCuron(java.math.BigDecimal curon) {
		set("curon", curon);
	}

	public java.math.BigDecimal getCuron() {
		return get("curon");
	}

	public void setEngineLoad(java.math.BigDecimal engineLoad) {
		set("engine_load", engineLoad);
	}

	public java.math.BigDecimal getEngineLoad() {
		return get("engine_load");
	}

	public void setDpfBeforeTemperature(java.math.BigDecimal dpfBeforeTemperature) {
		set("dpf_before_temperature", dpfBeforeTemperature);
	}

	public java.math.BigDecimal getDpfBeforeTemperature() {
		return get("dpf_before_temperature");
	}

	public void setDpfArterTemperature(java.math.BigDecimal dpfArterTemperature) {
		set("dpf_arter_temperature", dpfArterTemperature);
	}

	public java.math.BigDecimal getDpfArterTemperature() {
		return get("dpf_arter_temperature");
	}

	public void setUreaTemperature(java.math.BigDecimal ureaTemperature) {
		set("urea_temperature", ureaTemperature);
	}

	public java.math.BigDecimal getUreaTemperature() {
		return get("urea_temperature");
	}

	public void setUreaPosition(java.math.BigDecimal ureaPosition) {
		set("urea_position", ureaPosition);
	}

	public java.math.BigDecimal getUreaPosition() {
		return get("urea_position");
	}

	public void setTemperature1(java.math.BigDecimal temperature1) {
		set("temperature_1", temperature1);
	}

	public java.math.BigDecimal getTemperature1() {
		return get("temperature_1");
	}

	public void setTemperature2(java.math.BigDecimal temperature2) {
		set("temperature_2", temperature2);
	}

	public java.math.BigDecimal getTemperature2() {
		return get("temperature_2");
	}

	public void setTemperature3(java.math.BigDecimal temperature3) {
		set("temperature_3", temperature3);
	}

	public java.math.BigDecimal getTemperature3() {
		return get("temperature_3");
	}

	public void setTemperature4(java.math.BigDecimal temperature4) {
		set("temperature_4", temperature4);
	}

	public java.math.BigDecimal getTemperature4() {
		return get("temperature_4");
	}

	public void setPressure(java.math.BigDecimal pressure) {
		set("pressure", pressure);
	}

	public java.math.BigDecimal getPressure() {
		return get("pressure");
	}

	public void setReportTime(java.util.Date reportTime) {
		set("report_time", reportTime);
	}

	public java.util.Date getReportTime() {
		return get("report_time");
	}

	public void setFlagMileage(Integer flagMileage) {
		set("flag_mileage", flagMileage);
	}

	public Integer getFlagMileage() {
		return get("flag_mileage");
	}

	public void setFlagSpeed(Integer flagSpeed) {
		set("flag_speed", flagSpeed);
	}

	public Integer getFlagSpeed() {
		return get("flag_speed");
	}

	public void setTemperature1Flag(Integer temperature1Flag) {
		set("temperature_1_flag", temperature1Flag);
	}

	public Integer getTemperature1Flag() {
		return get("temperature_1_flag");
	}

	public void setUreaTemperatureFlag(Integer ureaTemperatureFlag) {
		set("urea_temperature_flag", ureaTemperatureFlag);
	}

	public Integer getUreaTemperatureFlag() {
		return get("urea_temperature_flag");
	}

	public void setUreaPositionFlag(Integer ureaPositionFlag) {
		set("urea_position_flag", ureaPositionFlag);
	}

	public Integer getUreaPositionFlag() {
		return get("urea_position_flag");
	}

	public void setTemperature2Flag(Integer temperature2Flag) {
		set("temperature_2_flag", temperature2Flag);
	}

	public Integer getTemperature2Flag() {
		return get("temperature_2_flag");
	}

	public void setTemperature3Flag(Integer temperature3Flag) {
		set("temperature_3_flag", temperature3Flag);
	}

	public Integer getTemperature3Flag() {
		return get("temperature_3_flag");
	}

	public void setTemperature4Flag(Integer temperature4Flag) {
		set("temperature_4_flag", temperature4Flag);
	}

	public Integer getTemperature4Flag() {
		return get("temperature_4_flag");
	}

	public void setPressureFlag(Integer pressureFlag) {
		set("pressure_flag", pressureFlag);
	}

	public Integer getPressureFlag() {
		return get("pressure_flag");
	}

	public void setPmValue(java.math.BigDecimal pmValue) {
		set("pm_value", pmValue);
	}

	public java.math.BigDecimal getPmValue() {
		return get("pm_value");
	}

	public void setNoValue(java.math.BigDecimal noValue) {
		set("no_value", noValue);
	}

	public java.math.BigDecimal getNoValue() {
		return get("no_value");
	}

	public void setNoValueFlag(Integer noValueFlag) {
		set("no_value_flag", noValueFlag);
	}

	public Integer getNoValueFlag() {
		return get("no_value_flag");
	}

	public void setPmValueFlag(Integer pmValueFlag) {
		set("pm_value_flag", pmValueFlag);
	}

	public Integer getPmValueFlag() {
		return get("pm_value_flag");
	}

	public void setCode(java.math.BigDecimal code) {
		set("code", code);
	}

	public java.math.BigDecimal getCode() {
		return get("code");
	}

	public void setGpsId(java.math.BigInteger gpsId) {
		set("gps_id", gpsId);
	}

	public java.math.BigInteger getGpsId() {
		return get("gps_id");
	}

}
