/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.device.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDevice<M extends BaseDevice<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setBatchId(Integer batchId) {
		set("batch_id", batchId);
	}

	public Integer getBatchId() {
		return get("batch_id");
	}

	public void setDeviceCode(String deviceCode) {
		set("device_code", deviceCode);
	}

	public String getDeviceCode() {
		return get("device_code");
	}

	public void setAuthCode(String authCode) {
		set("auth_code", authCode);
	}

	public String getAuthCode() {
		return get("auth_code");
	}

	public void setDeviceModel(String deviceModel) {
		set("device_model", deviceModel);
	}

	public String getDeviceModel() {
		return get("device_model");
	}

	public void setOperator(Integer operator) {
		set("operator", operator);
	}

	public Integer getOperator() {
		return get("operator");
	}

	public void setDateline(java.util.Date dateline) {
		set("dateline", dateline);
	}

	public java.util.Date getDateline() {
		return get("dateline");
	}

	public void setStatus(Boolean status) {
		set("status", status);
	}

	public Boolean getStatus() {
		return get("status");
	}

}
