/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.device.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceStatus<M extends BaseDeviceStatus<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setDeviceId(java.math.BigInteger deviceId) {
		set("device_id", deviceId);
	}

	public java.math.BigInteger getDeviceId() {
		return get("device_id");
	}

	public void setExhaustStatus(Integer exhaustStatus) {
		set("exhaust_status", exhaustStatus);
	}

	public Integer getExhaustStatus() {
		return get("exhaust_status");
	}

	public void setCarStatus(Integer carStatus) {
		set("car_status", carStatus);
	}

	public Integer getCarStatus() {
		return get("car_status");
	}

	public void setReportTime(java.util.Date reportTime) {
		set("report_time", reportTime);
	}

	public java.util.Date getReportTime() {
		return get("report_time");
	}

}
