/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.device.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceWarning<M extends BaseDeviceWarning<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setDeviceId(Long deviceId) {
		set("device_id", deviceId);
	}

	public Long getDeviceId() {
		return get("device_id");
	}

	public void setCategory(Integer category) {
		set("category", category);
	}

	public Integer getCategory() {
		return get("category");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setWarningTime(java.util.Date warningTime) {
		set("warning_time", warningTime);
	}

	public java.util.Date getWarningTime() {
		return get("warning_time");
	}

	public void setHistoryDataId(Long historyDataId) {
		set("history_data_id", historyDataId);
	}

	public Long getHistoryDataId() {
		return get("history_data_id");
	}

}
