/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.sys.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDict<M extends BaseDict<M>> extends Model<M> implements IBean {

    public Integer getId() {
        return get("id");
    }

    public void setId(Integer id) {
        set("id", id);
    }

    public String getCode() {
        return get("code");
    }

    public void setCode(String code) {
        set("code", code);
    }

    public String getName() {
        return get("name");
    }

    public void setName(String name) {
        set("name", name);
    }

    public String getDescription() {
        return get("description");
    }

    public void setDescription(String description) {
        set("description", description);
    }

    public Integer getParent() {
        return get("parent");
    }

    public void setParent(Integer parent) {
        set("parent", parent);
    }

    public Boolean getEnabled() {
        return get("enabled");
    }

    public void setEnabled(Boolean enabled) {
        set("enabled", enabled);
    }

    public Integer getOrderCode() {
        return get("order_code");
    }

    public void setOrderCode(Integer orderCode) {
        set("order_code", orderCode);
    }

    public Integer getLevelCode() {
        return get("level_code");
    }

    public void setLevelCode(Integer levelCode) {
        set("level_code", levelCode);
    }

}
