/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.sys.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResources<M extends BaseResources<M>> extends Model<M> implements IBean {

    public Integer getId() {
        return get("id");
    }

    public void setId(Integer id) {
        set("id", id);
    }

    public String getCode() {
        return get("code");
    }

    public void setCode(String code) {
        set("code", code);
    }

    public String getName() {
        return get("name");
    }

    public void setName(String name) {
        set("name", name);
    }

    public String getShowName() {
        return get("show_name");
    }

    public void setShowName(String showName) {
        set("show_name", showName);
    }

    public String getStyle() {
        return get("style");
    }

    public void setStyle(String style) {
        set("style", style);
    }

    public String getPath() {
        return get("path");
    }

    public void setPath(String path) {
        set("path", path);
    }

    public String getIcon() {
        return get("icon");
    }

    public void setIcon(String icon) {
        set("icon", icon);
    }

    public String getDescription() {
        return get("description");
    }

    public void setDescription(String description) {
        set("description", description);
    }

    public Integer getStatus() {
        return get("status");
    }

    public void setStatus(Integer status) {
        set("status", status);
    }

    public Integer getParent() {
        return get("parent");
    }

    public void setParent(Integer parent) {
        set("parent", parent);
    }

    public Integer getSort() {
        return get("sort");
    }

    public void setSort(Integer sort) {
        set("sort", sort);
    }

}
