/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.sys.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArea<M extends BaseArea<M>> extends Model<M> implements IBean {

    public Integer getId() {
        return get("id");
    }

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getLevel() {
        return get("level");
    }

    public void setLevel(Integer level) {
        set("level", level);
    }

    public Integer getParent() {
        return get("parent");
    }

    public void setParent(Integer parent) {
        set("parent", parent);
    }

    public String getName() {
        return get("name");
    }

    public void setName(String name) {
        set("name", name);
    }

    public String getSn() {
        return get("sn");
    }

    public void setSn(String sn) {
        set("sn", sn);
    }

}
