/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSecurityLog<M extends BaseSecurityLog<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setUser(Integer user) {
		set("user", user);
	}

	public Integer getUser() {
		return get("user");
	}

	public void setUsername(String username) {
		set("username", username);
	}

	public String getUsername() {
		return get("username");
	}

	public void setOrgname(String orgname) {
		set("orgname", orgname);
	}

	public String getOrgname() {
		return get("orgname");
	}

	public void setResource(Integer resource) {
		set("resource", resource);
	}

	public Integer getResource() {
		return get("resource");
	}

	public void setModuleName(String moduleName) {
		set("module_name", moduleName);
	}

	public String getModuleName() {
		return get("module_name");
	}

	public void setOprStarttime(java.util.Date oprStarttime) {
		set("opr_starttime", oprStarttime);
	}

	public java.util.Date getOprStarttime() {
		return get("opr_starttime");
	}

	public void setOprEndtime(java.util.Date oprEndtime) {
		set("opr_endtime", oprEndtime);
	}

	public java.util.Date getOprEndtime() {
		return get("opr_endtime");
	}

	public void setOprType(Integer oprType) {
		set("opr_type", oprType);
	}

	public Integer getOprType() {
		return get("opr_type");
	}

	public void setOprContent(String oprContent) {
		set("opr_content", oprContent);
	}

	public String getOprContent() {
		return get("opr_content");
	}

	public void setLoginIp(String loginIp) {
		set("login_ip", loginIp);
	}

	public String getLoginIp() {
		return get("login_ip");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
