/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.sys.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSettings<M extends BaseSettings<M>> extends Model<M> implements IBean {

    public String getId() {
        return get("id");
    }

    public void setId(String id) {
        set("id", id);
    }

    public String getItem() {
        return get("item");
    }

    public void setItem(String item) {
        set("item", item);
    }

    public String getName() {
        return get("name");
    }

    public void setName(String name) {
        set("name", name);
    }

    public String getContent() {
        return get("content");
    }

    public void setContent(String content) {
        set("content", content);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

    public String getDescription() {
        return get("description");
    }

    public void setDescription(String description) {
        set("description", description);
    }

    public String getCreateUser() {
        return get("create_user");
    }

    public void setCreateUser(String createUser) {
        set("create_user", createUser);
    }

    public Integer getLastUpdateUser() {
        return get("last_update_user");
    }

    public void setLastUpdateUser(Integer lastUpdateUser) {
        set("last_update_user", lastUpdateUser);
    }

    public java.util.Date getLastUpdateTime() {
        return get("last_update_time");
    }

    public void setLastUpdateTime(java.util.Date lastUpdateTime) {
        set("last_update_time", lastUpdateTime);
    }

    public Boolean getDefaultFlag() {
        return get("default_flag");
    }

    public void setDefaultFlag(Boolean defaultFlag) {
        set("default_flag", defaultFlag);
    }

}
