/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.info.base;


import com.mo008.crdm.models.info.Notice;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

    public Integer getId() {
        return get("id");
    }

    public void setId(Integer id) {
        set("id", id);
    }

    public String getTitle() {
        return get("title");
    }

    public void setTitle(String title) {
        set("title", title);
    }

    public String getSummary() {
        return get("summary");
    }

    public void setSummary(String summary) {
        set("summary", summary);
    }

    public String getContent() {
        return get("content");
    }

    public void setContent(String content) {
        set("content", content);
    }

    public Boolean getTopFlag() {
        return get("top_flag");
    }

    public void setTopFlag(Boolean topFlag) {
        set("top_flag", topFlag);
    }

    public java.util.Date getPublishTime() {
        return get("publish_time");
    }

    public void setPublishTime(java.util.Date publishTime) {
        set("publish_time", publishTime);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

    public Notice.Status getStatus() {
        int status = getInt("status");
        switch (status) {
            case 0:
                return Notice.Status.NEW;
            case 1:
                return Notice.Status.PUBLISHED;
            case 2:
                return Notice.Status.UNPUBLISH;
            case 3:
                return Notice.Status.DELETE;
        }
        return Notice.Status.NEW;
    }

    public void setStatus(Notice.Status status) {
        set("status", status.getStatus());
    }

    public Integer getPublisher() {
        return get("publisher");
    }

    public void setPublisher(Integer publisher) {
        set("publisher", publisher);
    }

    public Boolean getDeleteFlag() {
        return get("delete_flag");
    }

    public void setDeleteFlag(Boolean deleteFlag) {
        set("delete_flag", deleteFlag);
    }

    public java.util.Date getDeleteTime() {
        return get("delete_time");
    }

    public void setDeleteTime(java.util.Date deleteTime) {
        set("delete_time", deleteTime);
    }

    public Integer getDeleteUser() {
        return get("delete_user");
    }

    public void setDeleteUser(Integer deleteUser) {
        set("delete_user", deleteUser);
    }

    public Integer getOrderNo() {
        return get("order_no");
    }

    public void setOrderNo(Integer orderNo) {
        set("order_no", orderNo);
    }

}
