/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.info.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNoticeView<M extends BaseNoticeView<M>> extends Model<M> implements IBean {

    public Integer getNoticeId() {
        return get("notice_id");
    }

    public void setNoticeId(Integer noticeId) {
        set("notice_id", noticeId);
    }

    public Integer getUserId() {
        return get("user_id");
    }

    public void setUserId(Integer userId) {
        set("user_id", userId);
    }

    public java.util.Date getViewTime() {
        return get("view_time");
    }

    public void setViewTime(java.util.Date viewTime) {
        set("view_time", viewTime);
    }

}
