/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.sys;

import com.mo008.crdm.models.sys.base.BaseAttachment;

import goja.core.annotation.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "mo_attachment")
public class Attachment extends BaseAttachment<Attachment> {
	public static final Attachment dao = new Attachment();
}
