/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.sys;

import com.mo008.crdm.models.sys.base.BaseSecurityLog;

import goja.core.annotation.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "mo_security_log")
public class SecurityLog extends BaseSecurityLog<SecurityLog> {
	public static final SecurityLog dao = new SecurityLog();
	private static final long serialVersionUID = -1955282840201314849L;
}
