package com.mo008.crdm.models.supplier;


import com.google.common.base.MoreObjects;

import com.mo008.crdm.models.supplier.base.BaseSupplier;

import goja.core.annotation.TableBind;
import goja.core.sqlinxml.SqlKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "mo_supplier")
public class Supplier extends BaseSupplier<Supplier> {
    public static final Supplier dao = new Supplier();


    public boolean checkCarNo(String carNo, String terminal) {
        final String sql = SqlKit.sql("supplier.checkcarno");
        return findFirst(sql, carNo, terminal) == null;
    }

    public Supplier findByName(String supplierName) {
        final String sql = SqlKit.sql("supplier.selectByName");
        return findFirst(sql, supplierName);
    }

    public Supplier findByNameAndCarNo(String supplierName, String carNo) {
        final String sql = SqlKit.sql("supplier.findByNameAndCarNo");
        return findFirst(sql, supplierName, carNo);
    }

    public Supplier findByCarNo(String carNo) {
        final String sql = SqlKit.sql("supplier.findByCarNo");
        return findFirst(sql, carNo);
    }

    public int countBySpplierId(Integer supplierId) {
        final String sql = SqlKit.sql("supplier.countBySpplierId");
        final Number cnt = findFirst(sql, supplierId).getNumber("cnt");
        if(cnt == null){
            return 0;
        }
        return cnt.intValue();
    }
}
