package com.mo008.crdm.models.supplier;


import com.jfinal.plugin.activerecord.Db;
import com.mo008.crdm.models.supplier.base.BaseSupplierCar;

import goja.core.annotation.TableBind;
import goja.core.sqlinxml.SqlKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "mo_supplier_car")
public class SupplierCar extends BaseSupplierCar<SupplierCar> {
    public static final SupplierCar dao = new SupplierCar();

    public boolean deleteBySupplier(int supplierId) {
        final String sql = SqlKit.sql("supplier.car.deleteBySupplier");
        return Db.update(sql, supplierId) >= 0;
    }
}
