/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.car.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarGps<M extends BaseCarGps<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setDeviceId(Integer deviceId) {
		set("device_id", deviceId);
	}

	public Integer getDeviceId() {
		return get("device_id");
	}

	public void setGpsLongitude(String gpsLongitude) {
		set("gps_longitude", gpsLongitude);
	}

	public String getGpsLongitude() {
		return get("gps_longitude");
	}

	public void setGpsLatitude(String gpsLatitude) {
		set("gps_latitude", gpsLatitude);
	}

	public String getGpsLatitude() {
		return get("gps_latitude");
	}

	public void setBaiduLongitude(Double baiduLongitude) {
		set("baidu_longitude", baiduLongitude);
	}

	public Double getBaiduLongitude() {
		return get("baidu_longitude");
	}

	public void setBaiduLatitude(Double baiduLatitude) {
		set("baidu_latitude", baiduLatitude);
	}

	public Double getBaiduLatitude() {
		return get("baidu_latitude");
	}

	public void setTimestamp(Long timestamp) {
		set("timestamp", timestamp);
	}

	public Long getTimestamp() {
		return get("timestamp");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDeviceData(Long deviceData) {
		set("device_data", deviceData);
	}

	public Long getDeviceData() {
		return get("device_data");
	}

}
