/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.car.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarInfo<M extends BaseCarInfo<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setDeviceId(Long deviceId) {
		set("device_id", deviceId);
	}

	public Long getDeviceId() {
		return get("device_id");
	}

	public void setCarNo(String carNo) {
		set("car_no", carNo);
	}

	public String getCarNo() {
		return get("car_no");
	}

	public void setCarNoColor(Integer carNoColor) {
		set("car_no_color", carNoColor);
	}

	public Integer getCarNoColor() {
		return get("car_no_color");
	}

	public void setCarFlag(String carFlag) {
		set("car_flag", carFlag);
	}

	public String getCarFlag() {
		return get("car_flag");
	}

	public void setCarFrameworkNo(String carFrameworkNo) {
		set("car_framework_no", carFrameworkNo);
	}

	public String getCarFrameworkNo() {
		return get("car_framework_no");
	}

	public void setCarModel(String carModel) {
		set("car_model", carModel);
	}

	public String getCarModel() {
		return get("car_model");
	}

	public void setAgent(String agent) {
		set("agent", agent);
	}

	public String getAgent() {
		return get("agent");
	}

	public void setDriverId(Integer driverId) {
		set("driver_id", driverId);
	}

	public Integer getDriverId() {
		return get("driver_id");
	}

	public void setAreaSn(String areaSn) {
		set("area_sn", areaSn);
	}

	public String getAreaSn() {
		return get("area_sn");
	}

	public void setEngineModel(Integer engineModel) {
		set("engine_model", engineModel);
	}

	public Integer getEngineModel() {
		return get("engine_model");
	}

	public void setEnginePower(java.math.BigDecimal enginePower) {
		set("engine_power", enginePower);
	}

	public java.math.BigDecimal getEnginePower() {
		return get("engine_power");
	}

	public void setEngineDischargeValue(java.math.BigDecimal engineDischargeValue) {
		set("engine_discharge_value", engineDischargeValue);
	}

	public java.math.BigDecimal getEngineDischargeValue() {
		return get("engine_discharge_value");
	}

	public void setEngineGassType(Integer engineGassType) {
		set("engine_gass_type", engineGassType);
	}

	public Integer getEngineGassType() {
		return get("engine_gass_type");
	}

	public void setSimCard(String simCard) {
		set("sim_card", simCard);
	}

	public String getSimCard() {
		return get("sim_card");
	}

	public void setTerminal(String terminal) {
		set("terminal", terminal);
	}

	public String getTerminal() {
		return get("terminal");
	}

	public void setDisplayFlag(Integer displayFlag) {
		set("display_flag", displayFlag);
	}

	public Integer getDisplayFlag() {
		return get("display_flag");
	}

	public void setCarDischargeStandard(String carDischargeStandard) {
		set("car_discharge_standard", carDischargeStandard);
	}

	public String getCarDischargeStandard() {
		return get("car_discharge_standard");
	}

	public void setInitalSmokeValue(java.math.BigDecimal initalSmokeValue) {
		set("inital_smoke_value", initalSmokeValue);
	}

	public java.math.BigDecimal getInitalSmokeValue() {
		return get("inital_smoke_value");
	}

	public void setWheelPower(java.math.BigDecimal wheelPower) {
		set("wheel_power", wheelPower);
	}

	public java.math.BigDecimal getWheelPower() {
		return get("wheel_power");
	}

	public void setInitalSmoke80Value(java.math.BigDecimal initalSmoke80Value) {
		set("inital_smoke_80_value", initalSmoke80Value);
	}

	public java.math.BigDecimal getInitalSmoke80Value() {
		return get("inital_smoke_80_value");
	}

	public void setInitalSmoke100Value(java.math.BigDecimal initalSmoke100Value) {
		set("inital_smoke_100_value", initalSmoke100Value);
	}

	public java.math.BigDecimal getInitalSmoke100Value() {
		return get("inital_smoke_100_value");
	}

	public void setInitalSmoke90Value(java.math.BigDecimal initalSmoke90Value) {
		set("inital_smoke_90_value", initalSmoke90Value);
	}

	public java.math.BigDecimal getInitalSmoke90Value() {
		return get("inital_smoke_90_value");
	}

	public void setInitalH2O2Value(java.math.BigDecimal initalH2O2Value) {
		set("inital_h2_o2_value", initalH2O2Value);
	}

	public java.math.BigDecimal getInitalH2O2Value() {
		return get("inital_h2_o2_value");
	}

	public void setStatus(Boolean status) {
		set("status", status);
	}

	public Boolean getStatus() {
		return get("status");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setAfterSmokeValue(java.math.BigDecimal afterSmokeValue) {
		set("after_smoke_value", afterSmokeValue);
	}

	public java.math.BigDecimal getAfterSmokeValue() {
		return get("after_smoke_value");
	}

	public void setAfterWheelPower(java.math.BigDecimal afterWheelPower) {
		set("after_wheel_power", afterWheelPower);
	}

	public java.math.BigDecimal getAfterWheelPower() {
		return get("after_wheel_power");
	}

	public void setAfterSmoke80Value(java.math.BigDecimal afterSmoke80Value) {
		set("after_smoke_80_value", afterSmoke80Value);
	}

	public java.math.BigDecimal getAfterSmoke80Value() {
		return get("after_smoke_80_value");
	}

	public void setAfterSmoke100Value(java.math.BigDecimal afterSmoke100Value) {
		set("after_smoke_100_value", afterSmoke100Value);
	}

	public java.math.BigDecimal getAfterSmoke100Value() {
		return get("after_smoke_100_value");
	}

	public void setAfterSmoke90Value(java.math.BigDecimal afterSmoke90Value) {
		set("after_smoke_90_value", afterSmoke90Value);
	}

	public java.math.BigDecimal getAfterSmoke90Value() {
		return get("after_smoke_90_value");
	}

	public void setAfterH2O2Value(java.math.BigDecimal afterH2O2Value) {
		set("after_h2_o2_value", afterH2O2Value);
	}

	public java.math.BigDecimal getAfterH2O2Value() {
		return get("after_h2_o2_value");
	}

	public void setOperator(Integer operator) {
		set("operator", operator);
	}

	public Integer getOperator() {
		return get("operator");
	}

}
