/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.car.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarFailureCriteria<M extends BaseCarFailureCriteria<M>> extends Model<M> implements IBean {

	public void setCarId(Integer carId) {
		set("car_id", carId);
	}

	public Integer getCarId() {
		return get("car_id");
	}

	public void setMinMileage(java.math.BigDecimal minMileage) {
		set("min_mileage", minMileage);
	}

	public java.math.BigDecimal getMinMileage() {
		return get("min_mileage");
	}

	public void setMaxMileage(java.math.BigDecimal maxMileage) {
		set("max_mileage", maxMileage);
	}

	public java.math.BigDecimal getMaxMileage() {
		return get("max_mileage");
	}

	public void setMinSpeed(java.math.BigDecimal minSpeed) {
		set("min_speed", minSpeed);
	}

	public java.math.BigDecimal getMinSpeed() {
		return get("min_speed");
	}

	public void setMaxSpeed(java.math.BigDecimal maxSpeed) {
		set("max_speed", maxSpeed);
	}

	public java.math.BigDecimal getMaxSpeed() {
		return get("max_speed");
	}

	public void setTemperature1Max(java.math.BigDecimal temperature1Max) {
		set("temperature_1_max", temperature1Max);
	}

	public java.math.BigDecimal getTemperature1Max() {
		return get("temperature_1_max");
	}

	public void setTemperature1Min(java.math.BigDecimal temperature1Min) {
		set("temperature_1_min", temperature1Min);
	}

	public java.math.BigDecimal getTemperature1Min() {
		return get("temperature_1_min");
	}

	public void setUreaTemperatureMax(java.math.BigDecimal ureaTemperatureMax) {
		set("urea_temperature_max", ureaTemperatureMax);
	}

	public java.math.BigDecimal getUreaTemperatureMax() {
		return get("urea_temperature_max");
	}

	public void setUreaTemperatureMin(java.math.BigDecimal ureaTemperatureMin) {
		set("urea_temperature_min", ureaTemperatureMin);
	}

	public java.math.BigDecimal getUreaTemperatureMin() {
		return get("urea_temperature_min");
	}

	public void setUreaPositionMax(java.math.BigDecimal ureaPositionMax) {
		set("urea_position_max", ureaPositionMax);
	}

	public java.math.BigDecimal getUreaPositionMax() {
		return get("urea_position_max");
	}

	public void setUreaPositionMin(java.math.BigDecimal ureaPositionMin) {
		set("urea_position_min", ureaPositionMin);
	}

	public java.math.BigDecimal getUreaPositionMin() {
		return get("urea_position_min");
	}

	public void setTemperature2Max(java.math.BigDecimal temperature2Max) {
		set("temperature_2_max", temperature2Max);
	}

	public java.math.BigDecimal getTemperature2Max() {
		return get("temperature_2_max");
	}

	public void setTemperature2Min(java.math.BigDecimal temperature2Min) {
		set("temperature_2_min", temperature2Min);
	}

	public java.math.BigDecimal getTemperature2Min() {
		return get("temperature_2_min");
	}

	public void setTemperature3Max(java.math.BigDecimal temperature3Max) {
		set("temperature_3_max", temperature3Max);
	}

	public java.math.BigDecimal getTemperature3Max() {
		return get("temperature_3_max");
	}

	public void setTemperature3Min(java.math.BigDecimal temperature3Min) {
		set("temperature_3_min", temperature3Min);
	}

	public java.math.BigDecimal getTemperature3Min() {
		return get("temperature_3_min");
	}

	public void setTemperature4Max(java.math.BigDecimal temperature4Max) {
		set("temperature_4_max", temperature4Max);
	}

	public java.math.BigDecimal getTemperature4Max() {
		return get("temperature_4_max");
	}

	public void setTemperature4Min(java.math.BigDecimal temperature4Min) {
		set("temperature_4_min", temperature4Min);
	}

	public java.math.BigDecimal getTemperature4Min() {
		return get("temperature_4_min");
	}

	public void setPressureMax(java.math.BigDecimal pressureMax) {
		set("pressure_max", pressureMax);
	}

	public java.math.BigDecimal getPressureMax() {
		return get("pressure_max");
	}

	public void setPressureMin(java.math.BigDecimal pressureMin) {
		set("pressure_min", pressureMin);
	}

	public java.math.BigDecimal getPressureMin() {
		return get("pressure_min");
	}

	public void setPmValueMax(java.math.BigDecimal pmValueMax) {
		set("pm_value_max", pmValueMax);
	}

	public java.math.BigDecimal getPmValueMax() {
		return get("pm_value_max");
	}

	public void setPmValueMin(java.math.BigDecimal pmValueMin) {
		set("pm_value_min", pmValueMin);
	}

	public java.math.BigDecimal getPmValueMin() {
		return get("pm_value_min");
	}

	public void setNoValueMax(java.math.BigDecimal noValueMax) {
		set("no_value_max", noValueMax);
	}

	public java.math.BigDecimal getNoValueMax() {
		return get("no_value_max");
	}

	public void setNoValueMin(java.math.BigDecimal noValueMin) {
		set("no_value_min", noValueMin);
	}

	public java.math.BigDecimal getNoValueMin() {
		return get("no_value_min");
	}

}
