/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.car.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarPicture<M extends BaseCarPicture<M>> extends Model<M> implements IBean {

	public void setAttenId(Integer attenId) {
		set("atten_id", attenId);
	}

	public Integer getAttenId() {
		return get("atten_id");
	}

	public void setCarId(Integer carId) {
		set("car_id", carId);
	}

	public Integer getCarId() {
		return get("car_id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
