/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.car;


import com.mo008.crdm.models.car.base.BaseCarPicture;

import goja.core.annotation.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "mo_car_picture", pks = {"atten_id","car_id"})
public class CarPicture extends BaseCarPicture<CarPicture> {
	public static final CarPicture dao = new CarPicture();
}
