/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.car;


import com.mo008.crdm.models.car.base.BaseDriver;

import goja.core.annotation.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "mo_driver")
public class Driver extends BaseDriver<Driver> {
	public static final Driver dao = new Driver();
	private static final long serialVersionUID = -2640441816771651764L;
}
