/*
 * Copyright © 2015-2016, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.mo008.crdm.models.car;


import com.mo008.crdm.models.car.base.BaseFence;
import goja.core.annotation.TableBind;
import goja.core.sqlinxml.SqlKit;

import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "mo_fence")
public class Fence extends BaseFence<Fence> {
	public static final Fence dao = new Fence();
	private static final long serialVersionUID = -3738692899598603000L;

	/**
	 * 查询所有的电子围栏
	 * @return
     */
	public List<Fence> findAll() {
		return find(SqlKit.sql("fence.findAll"));
	}
}
